services:
  wordpress:
    image: wordpress:6.9-php8.3-apache
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    environment:
      # Should not be here in a real environment
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
